SYMBOL: /[a-zA-Z_][a-zA-Z0-9_]*/
INT: /\d+/
WS: /\s+/
%ignore WS

fpcore: "(" "FPCore" "(" args ")" body ")" {FPCore}

args: id
    | id args        {Args}

body: expr

expr: id
    | num
    | "(" "+" expr expr ")"   {Add}
    | "(" "-" expr expr ")"   {Sub}
    | "(" "*" expr expr ")"   {Mul}
    | "(" "/" expr expr ")"   {Div}
    | "(" "-" expr ")"        {Neg}
    | "(" "sqrt" expr ")"     {Sqrt}

id: SYMBOL {Var}
num: INT {Num}
